import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

const admin = "00000000-0000-0000-0000-000000000001";
const gestora = "00000000-0000-0000-0000-000000000002";
const inativa = "00000000-0000-0000-0000-000000000003";
const vendedora = "00000000-0000-0000-0000-000000000004";
const outra = "00000000-0000-0000-0000-000000000005";

test("inclusão administrativa de lançamento de PA", async (t) => {
  const db = new PGlite();
  t.after(() => db.close());

  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as
      $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth, public to authenticated, anon;

    create table auth.users (id uuid primary key);
    create table public.perfis (id uuid primary key, nome text, papel text, ativo boolean);
    create table public.usuarios_pa (id uuid primary key, ativo boolean);
    create table public.lojas (
      id bigint primary key, codigo text, nome text, ativa boolean not null default true
    );
    create table public.dias_pa (
      id uuid primary key default gen_random_uuid(),
      usuario_id uuid not null,
      data date not null,
      situacao text not null,
      unique(usuario_id, data)
    );
    create table public.lancamentos_pa (
      id bigint generated by default as identity primary key,
      dia_id uuid not null,
      loja_id bigint not null,
      vendas integer not null check(vendas >= 0),
      pecas integer not null check(pecas >= vendas),
      atualizado_em timestamptz,
      unique(dia_id, loja_id)
    );

    alter table public.perfis enable row level security;
    alter table public.usuarios_pa enable row level security;
    alter table public.dias_pa enable row level security;
    alter table public.lancamentos_pa enable row level security;

    create policy perfil_proprio on public.perfis for select to authenticated using(id=auth.uid());
    create policy usuario_proprio on public.usuarios_pa for select to authenticated using(id=auth.uid());
    grant select on public.perfis, public.usuarios_pa to authenticated;

    insert into auth.users values
      ('${admin}'),('${gestora}'),('${inativa}'),('${vendedora}'),('${outra}');
    insert into public.perfis values
      ('${admin}','Admin','admin',true),
      ('${gestora}','Gestora','gestora',true),
      ('${inativa}','Inativa','admin',false),
      ('${vendedora}','Vendedora','vendedora',true);
    insert into public.usuarios_pa values ('${vendedora}',true),('${outra}',true);
    insert into public.lojas values
      (1,'CB','Clube Bijoux',true),
      (2,'AA','Arte Acessórios',true),
      (3,'AB','Adoro Bijoux',false);
  `);

  for (const name of [
    "20260903222000_criar_conferencias_pa.sql",
    "20260928225500_adicionar_lancamento_pa_gestao.sql",
  ]) {
    await db.exec(await readFile(new URL(`../supabase/migrations/${name}`, import.meta.url), "utf8"));
  }

  const asUser = async (id) => {
    await db.exec("reset role; set role authenticated;");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
  };

  const adicionar = (usuario = vendedora, data = "2026-09-02", loja = 1, vendas = 4, pecas = 9) =>
    db.query(
      "select public.adicionar_lancamento_pa_gestao($1,$2,$3,$4,$5) as id",
      [usuario, data, loja, vendas, pecas],
    );

  await t.test("vendedora e gestão inativa não adicionam", async () => {
    for (const id of [vendedora, inativa]) {
      await asUser(id);
      await assert.rejects(adicionar(), /Somente a gestão ativa/);
    }

    await db.exec("reset role; set role anon;");
    await assert.rejects(adicionar(), /permission denied/);
  });

  await t.test("gestora cria o dia e o lançamento no mesmo fluxo", async () => {
    await asUser(gestora);
    const resposta = await adicionar();
    assert.ok(resposta.rows[0].id);

    await db.exec("reset role");
    const dia = (await db.query(
      "select * from public.dias_pa where usuario_id=$1 and data=$2",
      [vendedora, "2026-09-02"],
    )).rows[0];
    assert.equal(dia.situacao, "trabalhado");

    const lancamento = (await db.query(
      "select * from public.lancamentos_pa where dia_id=$1 and loja_id=1",
      [dia.id],
    )).rows[0];
    assert.equal(lancamento.vendas, 4);
    assert.equal(lancamento.pecas, 9);
  });

  await t.test("novo lançamento invalida a aprovação da loja no mês", async () => {
    await db.exec(`insert into public.conferencias_pa values
      ('${vendedora}','2026-09-01',2,'${admin}',now());`);

    await asUser(admin);
    await adicionar(vendedora, "2026-09-02", 2, 2, 5);

    await db.exec("reset role");
    const aprovacoes = await db.query(
      "select loja_id from public.conferencias_pa where usuario_id=$1",
      [vendedora],
    );
    assert.equal(aprovacoes.rows.length, 0);
  });

  await t.test("duplicidade direciona para a correção", async () => {
    await asUser(admin);
    await assert.rejects(
      adicionar(vendedora, "2026-09-02", 1, 5, 10),
      /Já existe lançamento.*Use Corrigir/,
    );
  });

  await t.test("não sobrescreve dia marcado como não trabalhado", async () => {
    await db.exec(`reset role;
      insert into public.dias_pa (usuario_id,data,situacao)
      values ('${vendedora}','2026-09-03','ferias');`);

    await asUser(admin);
    await assert.rejects(
      adicionar(vendedora, "2026-09-03", 1, 1, 1),
      /está marcada como ferias/,
    );

    await db.exec("reset role");
    const dia = (await db.query(
      "select situacao from public.dias_pa where usuario_id=$1 and data='2026-09-03'",
      [vendedora],
    )).rows[0];
    assert.equal(dia.situacao, "ferias");
  });

  await t.test("valida loja e quantidades", async () => {
    await asUser(admin);
    await assert.rejects(adicionar(vendedora, "2026-09-04", 3, 1, 1), /loja ativa/);
    await assert.rejects(adicionar(vendedora, "2026-09-04", 1, 4, 3), /vendas e peças/);
    await assert.rejects(adicionar(outra, "2026-09-04", 1, -1, 1), /vendas e peças/);
  });
});
