import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

const gestora = "00000000-0000-0000-0000-000000000001";
const vendedora = "00000000-0000-0000-0000-000000000002";

test("fechamento do histórico de vendas", async (t) => {
  const db = new PGlite();
  t.after(() => db.close());

  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as
      $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth, public to authenticated, anon;

    create table auth.users (id uuid primary key);
    create table public.perfis (id uuid primary key, nome text, papel text, ativo boolean);
    create table public.vendas_diarias (
      id bigint generated by default as identity primary key,
      data date not null,
      valor_vendido numeric not null default 0
    );
    create table public.metas_mensais (
      id bigint generated by default as identity primary key,
      mes date not null,
      valor_meta numeric not null default 0
    );

    insert into auth.users values
      ('00000000-0000-0000-0000-000000000001'),
      ('00000000-0000-0000-0000-000000000002');

    insert into public.perfis values
      ('00000000-0000-0000-0000-000000000001','Gestora','gestora',true),
      ('00000000-0000-0000-0000-000000000002','Vendedora','vendedora',true);

    insert into public.vendas_diarias (data, valor_vendido)
    values
      (date_trunc('month', timezone('America/Sao_Paulo', now()))::date - 1, 100),
      (date_trunc('month', timezone('America/Sao_Paulo', now()))::date, 200);

    insert into public.metas_mensais (mes, valor_meta)
    values
      ((date_trunc('month', timezone('America/Sao_Paulo', now()))::date - interval '1 month')::date, 1000),
      (date_trunc('month', timezone('America/Sao_Paulo', now()))::date, 2000);
  `);

  await db.exec(
    await readFile(
      new URL("../supabase/migrations/20261007211459_fechamento_historico_vendas.sql", import.meta.url),
      "utf8",
    ),
  );

  const asUser = async (id) => {
    await db.exec("reset role; set role authenticated;");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
  };

  await t.test("vendedora não pode fechar o histórico", async () => {
    await asUser(vendedora);
    await assert.rejects(
      db.query("select public.fechar_historico_vendas()"),
      /Somente a gestão ativa/,
    );
  });

  await t.test("gestão fecha até o último dia do mês anterior", async () => {
    await asUser(gestora);
    const resposta = await db.query("select public.fechar_historico_vendas() as resultado");
    const esperado = await db.query(
      "select (date_trunc('month', timezone('America/Sao_Paulo', now()))::date - 1)::text as limite",
    );

    assert.equal(resposta.rows[0].resultado.fechado_ate, esperado.rows[0].limite);

    await db.exec("reset role");
    const fechamento = await db.query(
      "select fechado_ate::text, fechado_por from public.fechamento_vendas where id=1",
    );
    assert.equal(fechamento.rows.length, 1);
    assert.equal(fechamento.rows[0].fechado_ate, esperado.rows[0].limite);
    assert.equal(fechamento.rows[0].fechado_por, gestora);
  });

  await t.test("meses fechados bloqueiam vendas e metas", async () => {
    await db.exec("reset role");

    await assert.rejects(
      db.exec(`
        update public.vendas_diarias
        set valor_vendido=150
        where data < date_trunc('month', timezone('America/Sao_Paulo', now()))::date
      `),
      /somente para consulta/,
    );

    await assert.rejects(
      db.exec(`
        update public.metas_mensais
        set valor_meta=1500
        where mes < date_trunc('month', timezone('America/Sao_Paulo', now()))::date
      `),
      /somente para consulta/,
    );
  });

  await t.test("mês atual continua editável", async () => {
    await db.exec("reset role");

    await db.exec(`
      update public.vendas_diarias
      set valor_vendido=250
      where data = date_trunc('month', timezone('America/Sao_Paulo', now()))::date;

      update public.metas_mensais
      set valor_meta=2500
      where mes = date_trunc('month', timezone('America/Sao_Paulo', now()))::date;
    `);

    const venda = await db.query(`
      select valor_vendido::text
      from public.vendas_diarias
      where data = date_trunc('month', timezone('America/Sao_Paulo', now()))::date
    `);
    const meta = await db.query(`
      select valor_meta::text
      from public.metas_mensais
      where mes = date_trunc('month', timezone('America/Sao_Paulo', now()))::date
    `);

    assert.equal(venda.rows[0].valor_vendido, "250");
    assert.equal(meta.rows[0].valor_meta, "2500");
  });
});
