import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

const admin = "00000000-0000-0000-0000-000000000001";
const gestora = "00000000-0000-0000-0000-000000000002";
const vendedora = "00000000-0000-0000-0000-000000000003";

test("fechamento mensal do PA", async (t) => {
  const db = new PGlite();
  t.after(() => db.close());

  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as
      $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth, public to authenticated, anon;

    create table auth.users (id uuid primary key);
    create table public.perfis (id uuid primary key, nome text, papel text, ativo boolean);
    create table public.usuarios_pa (
      id uuid primary key,
      nome text not null,
      numero_athos integer,
      tipo_usuario text not null,
      ativo boolean not null
    );
    create table public.lojas (
      id bigint primary key,
      codigo text,
      nome text,
      ativa boolean not null default true
    );
    create table public.dias_pa (
      id uuid primary key default gen_random_uuid(),
      usuario_id uuid not null,
      data date not null,
      situacao text not null,
      observacao text,
      criado_em timestamptz not null default now(),
      atualizado_em timestamptz not null default now(),
      unique(usuario_id, data)
    );
    create table public.lancamentos_pa (
      id bigint generated by default as identity primary key,
      dia_id uuid not null,
      loja_id bigint not null,
      vendas integer not null,
      pecas integer not null,
      unique(dia_id, loja_id)
    );

    insert into auth.users values
      ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');
    insert into public.perfis values
      ('00000000-0000-0000-0000-000000000001','Admin','admin',true),
      ('00000000-0000-0000-0000-000000000002','Gestora','gestora',true),
      ('00000000-0000-0000-0000-000000000003','Vendedora','vendedora',true);
    insert into public.usuarios_pa values
      ('00000000-0000-0000-0000-000000000003','VENDEDORA',7,'vendedora',true);
    insert into public.lojas values (1,'CB','Clube Bijoux',true);

    insert into public.dias_pa (usuario_id,data,situacao)
    values ('00000000-0000-0000-0000-000000000003','2020-01-10','trabalhado');

    insert into public.lancamentos_pa (dia_id,loja_id,vendas,pecas)
    select id,1,2,5
    from public.dias_pa
    where usuario_id='00000000-0000-0000-0000-000000000003' and data='2020-01-10';
  `);

  for (const name of [
    "20260903222000_criar_conferencias_pa.sql",
    "20261005164500_fechamento_mensal_pa.sql",
  ]) {
    await db.exec(await readFile(new URL(`../supabase/migrations/${name}`, import.meta.url), "utf8"));
  }

  const asUser = async (id) => {
    await db.exec("reset role; set role authenticated;");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
  };

  await t.test("não fecha enquanto houver loja sem aprovação", async () => {
    await asUser(gestora);
    await assert.rejects(
      db.query("select public.fechar_mes_pa('2020-01-01')"),
      /Ainda existem lançamentos sem aprovação/,
    );
  });

  await t.test("gestão fecha depois da conferência completa", async () => {
    await db.exec(`reset role;
      insert into public.conferencias_pa
      values ('00000000-0000-0000-0000-000000000003','2020-01-01',1,'00000000-0000-0000-0000-000000000001',now());`);

    await asUser(gestora);
    const resposta = await db.query("select public.fechar_mes_pa('2020-01-01') as resultado");

    assert.equal(resposta.rows[0].resultado.mes, "2020-01-01");

    await db.exec("reset role");
    const fechamento = await db.query("select mes::text, fechado_por from public.fechamentos_pa");
    assert.equal(fechamento.rows.length, 1);
    assert.equal(fechamento.rows[0].mes, "2020-01-01");
    assert.equal(fechamento.rows[0].fechado_por, gestora);
  });

  await t.test("mês fechado bloqueia lançamentos, dias e aprovações", async () => {
    await db.exec("reset role");

    await assert.rejects(
      db.exec("update public.lancamentos_pa set pecas=6"),
      /mês está fechado/,
    );

    await assert.rejects(
      db.exec("update public.dias_pa set observacao='teste' where data='2020-01-10'"),
      /mês está fechado/,
    );

    await assert.rejects(
      db.exec("delete from public.conferencias_pa where mes='2020-01-01'"),
      /mês está fechado/,
    );
  });

  await t.test("gestora não reabre; administradora reabre", async () => {
    await asUser(gestora);
    await assert.rejects(
      db.query("select public.reabrir_mes_pa('2020-01-01')"),
      /Somente uma administradora ativa/,
    );

    await asUser(admin);
    await db.query("select public.reabrir_mes_pa('2020-01-01')");

    await db.exec("reset role");
    const fechamento = await db.query("select count(*)::int as total from public.fechamentos_pa");
    assert.equal(fechamento.rows[0].total, 0);

    await db.exec("update public.lancamentos_pa set pecas=6");
    const lancamento = await db.query("select pecas from public.lancamentos_pa");
    assert.equal(lancamento.rows[0].pecas, 6);
  });
});
