import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

const gestora = "00000000-0000-0000-0000-000000000001";
const vendedora = "00000000-0000-0000-0000-000000000002";

test("fechamento individual do mês de vendas", async (t) => {
  const db = new PGlite();
  t.after(() => db.close());

  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as
      $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth, public to authenticated, anon;

    create table auth.users (id uuid primary key);
    create table public.perfis (id uuid primary key, nome text, papel text, ativo boolean);
    create table public.lojas (
      id bigint primary key,
      codigo text,
      nome text,
      ativa boolean not null default true
    );
    create table public.vendas_diarias (
      id bigint generated by default as identity primary key,
      data date not null,
      loja_id bigint not null,
      periodo text not null,
      valor_vendido numeric not null default 0
    );
    create table public.metas_mensais (
      id bigint generated by default as identity primary key,
      mes date not null,
      loja_id bigint not null,
      periodo text not null,
      valor_meta numeric not null default 0
    );

    insert into auth.users values
      ('00000000-0000-0000-0000-000000000001'),
      ('00000000-0000-0000-0000-000000000002');

    insert into public.perfis values
      ('00000000-0000-0000-0000-000000000001','Gestora','gestora',true),
      ('00000000-0000-0000-0000-000000000002','Vendedora','vendedora',true);

    insert into public.lojas values (1,'CB','Clube Bijoux',true);

    insert into public.vendas_diarias (data,loja_id,periodo,valor_vendido)
    values
      ('2019-12-31',1,'manha',10),
      ('2020-01-31',1,'manha',100);

    insert into public.metas_mensais (mes,loja_id,periodo,valor_meta)
    values
      ('2019-12-01',1,'manha',500),
      ('2020-01-01',1,'manha',1000);
  `);

  await db.exec(
    await readFile(
      new URL("../supabase/migrations/20261007214500_fechamento_mensal_vendas.sql", import.meta.url),
      "utf8",
    ),
  );

  const asUser = async (id) => {
    await db.exec("reset role; set role authenticated;");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
  };

  await t.test("não fecha enquanto o último dia estiver incompleto", async () => {
    await asUser(gestora);
    await assert.rejects(
      db.query("select public.fechar_mes_vendas('2020-01-01')"),
      /Preencha manhã e noite/,
    );
  });

  await t.test("fecha apenas o mês selecionado depois do último dia completo", async () => {
    await db.exec("reset role");
    await db.exec("insert into public.vendas_diarias (data,loja_id,periodo,valor_vendido) values ('2020-01-31',1,'noite',120)");

    await asUser(gestora);
    const resposta = await db.query("select public.fechar_mes_vendas('2020-01-01') as resultado");
    assert.equal(resposta.rows[0].resultado.mes, "2020-01-01");

    await db.exec("reset role");
    const fechamentos = await db.query("select mes::text from public.fechamentos_vendas order by mes");
    assert.deepEqual(fechamentos.rows, [{ mes: "2020-01-01" }]);
  });

  await t.test("mês fechado bloqueia alterações sem bloquear o mês anterior", async () => {
    await db.exec("reset role");

    await assert.rejects(
      db.exec("update public.vendas_diarias set valor_vendido=130 where data='2020-01-31' and periodo='noite'"),
      /somente para consulta/,
    );
    await assert.rejects(
      db.exec("update public.metas_mensais set valor_meta=1100 where mes='2020-01-01'"),
      /somente para consulta/,
    );

    await db.exec("update public.vendas_diarias set valor_vendido=20 where data='2019-12-31'");
    await db.exec("update public.metas_mensais set valor_meta=600 where mes='2019-12-01'");

    const vendaAnterior = await db.query("select valor_vendido::text from public.vendas_diarias where data='2019-12-31'");
    assert.equal(vendaAnterior.rows[0].valor_vendido, "20");
  });

  await t.test("vendedora não pode fechar mês", async () => {
    await db.exec("reset role");
    await db.exec("insert into public.vendas_diarias (data,loja_id,periodo,valor_vendido) values ('2020-02-29',1,'manha',100),('2020-02-29',1,'noite',100)");

    await asUser(vendedora);
    await assert.rejects(
      db.query("select public.fechar_mes_vendas('2020-02-01')"),
      /Somente a gestão ativa/,
    );
  });
});
