import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

const admin = "00000000-0000-0000-0000-000000000001";
const gestora = "00000000-0000-0000-0000-000000000002";
const vendedora = "00000000-0000-0000-0000-000000000003";
const inativa = "00000000-0000-0000-0000-000000000004";

test("férias administrativas e resumo somente de vendedoras ativas", async (t) => {
  const db = new PGlite();
  t.after(() => db.close());

  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as
      $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth, public to authenticated, anon;

    create table auth.users (id uuid primary key);
    create table public.perfis (id uuid primary key, nome text, papel text, ativo boolean);
    create table public.usuarios_pa (
      id uuid primary key,
      nome text not null,
      numero_athos integer,
      tipo_usuario text not null,
      ativo boolean not null
    );
    create table public.lojas (
      id bigint primary key,
      codigo text,
      nome text,
      ativa boolean not null default true
    );
    create table public.dias_pa (
      id uuid primary key default gen_random_uuid(),
      usuario_id uuid not null,
      data date not null,
      situacao text not null,
      observacao text,
      criado_em timestamptz not null default now(),
      atualizado_em timestamptz not null default now(),
      unique(usuario_id, data)
    );
    create table public.lancamentos_pa (
      id bigint generated by default as identity primary key,
      dia_id uuid not null,
      loja_id bigint not null,
      vendas integer not null,
      pecas integer not null,
      unique(dia_id, loja_id)
    );

    insert into auth.users values
      ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003'),('00000000-0000-0000-0000-000000000004');
    insert into public.perfis values
      ('00000000-0000-0000-0000-000000000001','Admin','admin',true),
      ('00000000-0000-0000-0000-000000000002','Gestora','gestora',true),
      ('00000000-0000-0000-0000-000000000003','Vendedora','vendedora',true);
    insert into public.usuarios_pa values
      ('00000000-0000-0000-0000-000000000003','ATIVA',7,'vendedora',true),
      ('00000000-0000-0000-0000-000000000004','INATIVA',8,'vendedora',false);
    insert into public.lojas values (1,'CB','Clube Bijoux',true);

    insert into public.dias_pa (usuario_id,data,situacao) values
      ('00000000-0000-0000-0000-000000000003','2026-09-10','trabalhado'),
      ('00000000-0000-0000-0000-000000000004','2026-09-10','trabalhado');

    insert into public.lancamentos_pa (dia_id,loja_id,vendas,pecas)
    select id,1,2,5 from public.dias_pa where usuario_id='00000000-0000-0000-0000-000000000003';
    insert into public.lancamentos_pa (dia_id,loja_id,vendas,pecas)
    select id,1,1,2 from public.dias_pa where usuario_id='00000000-0000-0000-0000-000000000004';
  `);

  await db.exec(await readFile(
    new URL("../supabase/migrations/20260903222000_criar_conferencias_pa.sql", import.meta.url),
    "utf8",
  ));
  await db.exec(await readFile(
    new URL("../supabase/migrations/20260930162500_ferias_gestao_e_resumos_ativos.sql", import.meta.url),
    "utf8",
  ));

  const asUser = async (id) => {
    await db.exec("reset role; set role authenticated;");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
  };

  await t.test("resumo mensal esconde perfil desativado", async () => {
    await db.exec("reset role");
    const resumo = await db.query("select nome from public.resumo_pa_mensal order by nome");
    assert.deepEqual(resumo.rows.map((item) => item.nome), ["ATIVA"]);

    const porLoja = await db.query("select nome from public.resumo_pa_mensal_loja order by nome");
    assert.deepEqual(porLoja.rows.map((item) => item.nome), ["ATIVA"]);
  });

  await t.test("gestão registra intervalo e remove lançamentos existentes", async () => {
    await db.exec(`
      insert into public.conferencias_pa
      values ('00000000-0000-0000-0000-000000000003','2026-09-01',1,'00000000-0000-0000-0000-000000000001',now());
    `);

    await asUser(gestora);
    const resposta = await db.query(
      "select public.registrar_ferias_pa_gestao($1,$2,$3) as resultado",
      [vendedora, "2026-09-10", "2026-09-12"],
    );

    assert.equal(Number(resposta.rows[0].resultado.dias), 3);
    assert.equal(Number(resposta.rows[0].resultado.lancamentos_removidos), 1);

    await db.exec("reset role");
    const dias = await db.query(
      "select data::text, situacao from public.dias_pa where usuario_id=$1 and data between '2026-09-10' and '2026-09-12' order by data",
      [vendedora],
    );
    assert.equal(dias.rows.length, 3);
    assert.ok(dias.rows.every((item) => item.situacao === "ferias"));

    const lancamentos = await db.query(
      "select count(*)::int as total from public.lancamentos_pa l join public.dias_pa d on d.id=l.dia_id where d.usuario_id=$1",
      [vendedora],
    );
    assert.equal(lancamentos.rows[0].total, 0);

    const aprovacoes = await db.query(
      "select count(*)::int as total from public.conferencias_pa where usuario_id=$1",
      [vendedora],
    );
    assert.equal(aprovacoes.rows[0].total, 0);
  });

  await t.test("vendedora não pode registrar férias pela gestão", async () => {
    await asUser(vendedora);
    await assert.rejects(
      db.query("select public.registrar_ferias_pa_gestao($1,$2,$3)", [vendedora, "2026-10-01", "2026-10-05"]),
      /Somente a gestão ativa/,
    );
  });

  await t.test("não registra férias para perfil desativado nem intervalo inválido", async () => {
    await asUser(admin);
    await assert.rejects(
      db.query("select public.registrar_ferias_pa_gestao($1,$2,$3)", [inativa, "2026-10-01", "2026-10-05"]),
      /Vendedora ativa não encontrada/,
    );
    await assert.rejects(
      db.query("select public.registrar_ferias_pa_gestao($1,$2,$3)", [vendedora, "2026-10-05", "2026-10-01"]),
      /Confira as datas/,
    );
  });
});
