import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

const admin = "00000000-0000-0000-0000-000000000001";
const gestora = "00000000-0000-0000-0000-000000000002";
const inativa = "00000000-0000-0000-0000-000000000003";
const vendedora = "00000000-0000-0000-0000-000000000004";
const dia1 = "10000000-0000-0000-0000-000000000001";
const dia2 = "10000000-0000-0000-0000-000000000002";

test("remoção administrativa de lançamento de PA", async (t) => {
  const db = new PGlite();
  t.after(() => db.close());

  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable as
      $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth, public to authenticated, anon;

    create table auth.users (id uuid primary key);
    create table public.perfis (id uuid primary key, nome text, papel text, ativo boolean);
    create table public.usuarios_pa (id uuid primary key, ativo boolean);
    create table public.lojas (id bigint primary key, codigo text, nome text);
    create table public.dias_pa (
      id uuid primary key,
      usuario_id uuid not null,
      data date not null,
      situacao text not null,
      unique(usuario_id, data)
    );
    create table public.lancamentos_pa (
      id bigint generated by default as identity primary key,
      dia_id uuid not null,
      loja_id bigint not null,
      vendas integer not null,
      pecas integer not null,
      atualizado_em timestamptz,
      unique(dia_id, loja_id)
    );

    alter table public.perfis enable row level security;
    alter table public.usuarios_pa enable row level security;
    alter table public.lancamentos_pa enable row level security;

    create policy perfil_proprio on public.perfis for select to authenticated using(id=auth.uid());
    create policy usuario_proprio on public.usuarios_pa for select to authenticated using(id=auth.uid());
    grant select on public.perfis, public.usuarios_pa to authenticated;

    insert into auth.users values ('${admin}'),('${gestora}'),('${inativa}'),('${vendedora}');
    insert into public.perfis values
      ('${admin}','Admin','admin',true),
      ('${gestora}','Gestora','gestora',true),
      ('${inativa}','Inativa','admin',false),
      ('${vendedora}','Vendedora','vendedora',true);
    insert into public.usuarios_pa values ('${vendedora}',true);
    insert into public.lojas values
      (1,'CB','Clube Bijoux'),
      (2,'AA','Arte Acessórios');

    insert into public.dias_pa values
      ('${dia1}','${vendedora}','2026-09-15','trabalhado'),
      ('${dia2}','${vendedora}','2026-09-16','trabalhado');

    insert into public.lancamentos_pa (dia_id,loja_id,vendas,pecas) values
      ('${dia1}',1,5,11),
      ('${dia1}',2,2,5),
      ('${dia2}',1,5,11);
  `);

  for (const name of [
    "20260903222000_criar_conferencias_pa.sql",
    "20260904014006_correcoes_pa_com_notificacao.sql",
    "20260928235000_remover_lancamento_pa_gestao.sql",
  ]) {
    await db.exec(await readFile(new URL(`../supabase/migrations/${name}`, import.meta.url), "utf8"));
  }

  const asUser = async (id) => {
    await db.exec("reset role; set role authenticated;");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
  };

  const remover = (dia = dia1, data = "2026-09-15", loja = 1, vendas = 5, pecas = 11) =>
    db.query(
      "select public.remover_lancamento_pa_gestao($1,$2,$3,$4,$5,$6) as id",
      [vendedora, dia, data, loja, vendas, pecas],
    );

  await t.test("vendedora e gestão inativa não removem", async () => {
    for (const id of [vendedora, inativa]) {
      await asUser(id);
      await assert.rejects(remover(), /Somente a gestão ativa/);
    }
    await db.exec("reset role; set role anon;");
    await assert.rejects(remover(), /permission denied/);
  });

  await t.test("remove somente a loja escolhida, avisa e preserva o dia quando há outra loja", async () => {
    await db.exec(`reset role;
      insert into public.conferencias_pa values
        ('${vendedora}','2026-09-01',1,'${admin}',now()),
        ('${vendedora}','2026-09-01',2,'${admin}',now());`);

    await asUser(gestora);
    const resposta = await remover();
    assert.ok(resposta.rows[0].id);

    await db.exec("reset role");
    assert.equal((await db.query("select count(*)::int n from public.dias_pa where id=$1",[dia1])).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int n from public.lancamentos_pa where dia_id=$1 and loja_id=1",[dia1])).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from public.lancamentos_pa where dia_id=$1 and loja_id=2",[dia1])).rows[0].n, 1);

    const aviso = (await db.query("select * from public.correcoes_pa where dia_id=$1 order by criado_em desc limit 1",[dia1])).rows[0];
    assert.equal(aviso.vendas_antes, 5);
    assert.equal(aviso.pecas_antes, 11);
    assert.equal(aviso.vendas_depois, 0);
    assert.equal(aviso.pecas_depois, 0);
    assert.equal(aviso.motivo, "Lançamento removido pela gestão");
    assert.equal(aviso.corrigido_por_nome, "Gestora");
    assert.equal(aviso.lida_em, null);

    const aprovacoes = (await db.query(
      "select loja_id from public.conferencias_pa where usuario_id=$1 order by loja_id",
      [vendedora],
    )).rows.map((r) => Number(r.loja_id));
    assert.deepEqual(aprovacoes, [2]);
  });

  await t.test("remove o dia quando era o último lançamento e mantém o aviso", async () => {
    await asUser(admin);
    const resposta = await remover(dia2, "2026-09-16");
    const avisoId = resposta.rows[0].id;

    await db.exec("reset role");
    assert.equal((await db.query("select count(*)::int n from public.dias_pa where id=$1",[dia2])).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from public.correcoes_pa where id=$1",[avisoId])).rows[0].n, 1);
  });

  await t.test("não remove quando os valores mudaram ou o lançamento sumiu", async () => {
    await asUser(admin);
    await assert.rejects(
      db.query(
        "select public.remover_lancamento_pa_gestao($1,$2,$3,$4,$5,$6)",
        [vendedora,dia1,"2026-09-15",2,999,5],
      ),
      /lançamento mudou/i,
    );
    await assert.rejects(
      db.query(
        "select public.remover_lancamento_pa_gestao($1,$2,$3,$4,$5,$6)",
        [vendedora,dia1,"2026-09-15",1,5,11],
      ),
      /não existe mais/i,
    );
  });

  await t.test("falha no aviso impede a remoção", async () => {
    await db.exec(`reset role;
      insert into public.dias_pa values ('${dia2}','${vendedora}','2026-09-16','trabalhado');
      insert into public.lancamentos_pa (dia_id,loja_id,vendas,pecas) values ('${dia2}',1,5,11);
      create function public.falhar_aviso_remocao() returns trigger language plpgsql as
        $$begin raise exception 'Falha simulada no aviso'; end;$$;
      create trigger teste_falha_remocao before insert on public.correcoes_pa
        for each row execute function public.falhar_aviso_remocao();`);

    await asUser(admin);
    await assert.rejects(remover(dia2, "2026-09-16"), /Falha simulada no aviso/);

    await db.exec("reset role");
    assert.equal((await db.query("select count(*)::int n from public.lancamentos_pa where dia_id=$1",[dia2])).rows[0].n, 1);
  });
});
